name: Montents.com Build
on: 
  push:                               # master Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies    # 의존 파일 설치
        run: yarn install

      - name: make env file
        run: |
          echo 'USE_API_MOCK=true' > .env

      - name: Build                   # React Build
        run: yarn build

      #PutObject, PutObjectAcl 권한필요
      - name: Deploy                  # S3에 배포하기2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://montents.com --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
